# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    nbp_api.base_url: 'https://api.nbp.pl/api/exchangerates'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/App/Controller/'
        autowire: true
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\NbpApiService:
        arguments:
            $baseUrl: '%nbp_api.base_url%'

    App\Service\ExchangeRateRulesService:
            arguments:
                $rulesData:
                    - { code: 'USD', buy_offset: 0.15, sell_offset: 0.11 }
                    - { code: 'EUR', buy_offset: 0.15, sell_offset: 0.11 }
                    - { code: 'CZK', buy_offset: null, sell_offset: 0.20 }
                    - { code: 'IDR', buy_offset: null, sell_offset: 0.20 }
                    - { code: 'BRL', buy_offset: null, sell_offset: 0.20 }

    GuzzleHttp\Client:
        arguments:
            - { base_uri: '%nbp_api.base_url%' }